### ISSUE TITLE
TSNE duplicates

### ISSUE THREAD

**Issue by Kohze** [SpatialMap/SpatialMapDev#13]
While implementing the T-SNE / PCA toggle functionality i faced the issue that some datasets apparently have an error with active ```method = "t-SNE"``` regarding duplicates (while PCA works)
![kmzj2hzvrs2ci-1g5jdxua](https://user-images.githubusercontent.com/16598797/31577364-3b9e5a06-b10d-11e7-8e4a-28068b9fbe05.jpeg)

checking duplicates in exprs(object) turned out to have indeed a duplicated entry. 
![xzapxsqmtbwygrgx2tbfrq](https://user-images.githubusercontent.com/16598797/31577366-4680dba6-b10d-11e7-9356-b7cd1d1d45bb.jpeg)

Since we need a direct pipleline to add the T-SNE columns via the function call on the object, im wondering if an additional filter step might be usefull for the pRoloc plot2D tsne function. 

edit: the dataset name is E14TG2aS1

**Comment by lgatto** [comment]
Yes, that is well known for t-SNE. I'll add a filter with adequate message.

**Comment by lgatto** [comment]
Done in latest version (commit 61a83b43715bfb284cfc2d91fdb6b5cec1619689).
