### ISSUE TITLE
Handling of >10 profile columns

### ISSUE THREAD

**Issue by Kohze** [SpatialMap/SpatialMapDev#14]
In many datasets we get a extensive number of columns as seen in the image below.

![screenshot_117](https://user-images.githubusercontent.com/16598797/31866721-3823ee40-b784-11e7-948e-3c8b1d658279.jpg)

Since the columns are to dense to reveal work with, my question is if we either:
1. Specify a certain set of columns that should be displayed or 
2. Generally have a popup option to select/unselect displayed profile columns.

**Comment by Kohze** [comment]
![screenshot_118](https://user-images.githubusercontent.com/16598797/31866772-deaf973c-b784-11e7-8c74-63e0fc2c2fdb.jpg)

is a common & even more extrem case.

**Comment by lgatto** [comment]
A popup option to select/unselect displayed profile columns seems the best option.

**Comment by Kohze** [comment]
![untitled 1](https://user-images.githubusercontent.com/16598797/32199253-095cd2b8-bdcc-11e7-99e5-9112a2594bbb.png)

Added now a sidebar popup that is also scrollable in case the screenspace is not sufficient to show all columns. The advantage of the sidebar is that it does not hide the profile plot itself, making it a more interactive experience selecting the columns.

**Comment by lgatto** [comment]
Not sure if we need to toggle column names one by one, but we can change this later. The sidebar popup could be a general way to set various display options.
